# Generated by Django 4.0.4 on 2022-05-30 12:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(max_length=500, verbose_name='Հարց')),
                ('question_hy', ckeditor_uploader.fields.RichTextUploadingField(max_length=500, null=True, verbose_name='Հարց')),
                ('question_ru', ckeditor_uploader.fields.RichTextUploadingField(max_length=500, null=True, verbose_name='Հարց')),
                ('question_en', ckeditor_uploader.fields.RichTextUploadingField(max_length=500, null=True, verbose_name='Հարց')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Պատասխան')),
                ('answer_hy', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Պատասխան')),
                ('answer_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Պատասխան')),
                ('answer_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Պատասխան')),
            ],
            options={
                'verbose_name': 'Հաճախակի տրվող հարց',
                'verbose_name_plural': 'Հաճախակի տրվող հարցեր',
            },
        ),
    ]
