# Generated by Django 3.1 on 2022-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0002_auto_20220602_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpages',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Հղում'),
        ),
    ]
