# Generated by Django 4.0.4 on 2022-05-30 13:16

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Բաժնի անուն')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Հղում')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
                ('breadcrumbs_image', core.utils.CustomLogoField(blank=True, null=True, upload_to='gallery-category-bg/', verbose_name='Բաժնի բանների նկար')),
                ('breadcrumb_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ')),
            ],
            options={
                'verbose_name': 'Տեսադարանի բաժին',
                'verbose_name_plural': 'Տեսադարանի բաժիններ',
                'ordering': ['-my_order'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', core.utils.CustomLogoField(upload_to='gallery/')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Դասավորել')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallerycategory', verbose_name='Ընտրել բաժինը')),
            ],
            options={
                'verbose_name': 'Նկար',
                'verbose_name_plural': 'Տեսադարան',
                'ordering': ['-my_order'],
            },
        ),
    ]
