# Generated by Django 4.0.4 on 2022-05-30 13:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='breadcrumb_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='breadcrumb_text_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='breadcrumb_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն'),
        ),
    ]
