# Generated by Django 4.0.4 on 2022-05-30 12:37

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_hy', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_hy', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_ru', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_en', models.TextField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Բաժնի անուն')),
                ('name_hy', models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Բաժնի անուն')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Հղում')),
                ('breadcrumb_image', core.utils.CustomLogoField(blank=True, null=True, upload_to='blog-cat-bg-image/', verbose_name='Բաժնի բանների նկար')),
                ('breadcrumb_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ')),
                ('breadcrumb_text_hy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ')),
                ('breadcrumb_text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ')),
                ('breadcrumb_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Բանների տեքստ')),
            ],
            options={
                'verbose_name': 'Բլոգի բաժին',
                'verbose_name_plural': 'Բլոգի բաժիններ',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_hy', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_hy', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_ru', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_en', models.TextField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Վերնագիր')),
                ('name_hy', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Վերնագիր')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Հղում')),
                ('short_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ տեքստ')),
                ('short_text_hy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ տեքստ')),
                ('short_text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ տեքստ')),
                ('short_text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Հակիրճ տեքստ')),
                ('large_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ամբողջական տեքստ')),
                ('large_text_hy', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական տեքստ')),
                ('large_text_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական տեքստ')),
                ('large_text_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Ամբողջական տեքստ')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('image', core.utils.CustomLogoField(blank=True, null=True, upload_to='blog-image/', verbose_name='Գլխավոր նկար')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Ընտրել բաժինը')),
            ],
            options={
                'verbose_name': 'Բլոգ',
                'verbose_name_plural': 'Բլոգ',
            },
        ),
    ]
