# Generated by Django 4.0.4 on 2022-05-30 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_hy', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_hy', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_ru', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_description_en', models.TextField(blank=True, max_length=300, null=True)),
                ('iframe', models.TextField(blank=True, null=True, verbose_name='Քարտեզ (Iframe)')),
                ('breadcrumb_image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'svg', 'png', 'jpeg'])], verbose_name='Breadcrumb -ի Նկար')),
                ('breadcrumbs_text', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_hy', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_ru', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_en', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
            ],
            options={
                'verbose_name': 'Հետադարձ կապի էջ',
                'verbose_name_plural': 'Հետադարձ կապի էջ',
            },
        ),
        migrations.CreateModel(
            name='ContactUsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone1', models.CharField(blank=True, max_length=255)),
                ('messages', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Հետադարձ կապի պատվեր',
                'verbose_name_plural': 'Հետադարձ կապի պատվերներ',
            },
        ),
        migrations.CreateModel(
            name='FollowUsContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=400, verbose_name='Սոց. ցանցի անուն')),
                ('text_hy', models.CharField(max_length=400, null=True, verbose_name='Սոց. ցանցի անուն')),
                ('text_ru', models.CharField(max_length=400, null=True, verbose_name='Սոց. ցանցի անուն')),
                ('text_en', models.CharField(max_length=400, null=True, verbose_name='Սոց. ցանցի անուն')),
                ('icon', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'svg', 'png', 'jpeg'])], verbose_name='Նկար')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Հղում')),
                ('contact_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactus.contactuspage')),
            ],
            options={
                'verbose_name': 'Հետևեք մեզ - սոց. ցանցեր',
                'verbose_name_plural': 'Հետևեք մեզ - սոց. ցանցեր',
            },
        ),
        migrations.CreateModel(
            name='ContactUsJoinUsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=400, verbose_name='Տեքստ')),
                ('text_hy', models.CharField(max_length=400, null=True, verbose_name='Տեքստ')),
                ('text_ru', models.CharField(max_length=400, null=True, verbose_name='Տեքստ')),
                ('text_en', models.CharField(max_length=400, null=True, verbose_name='Տեքստ')),
                ('icon', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'svg', 'png', 'jpeg'])], verbose_name='Նկար')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Հղում')),
                ('contact_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactus.contactuspage')),
            ],
            options={
                'verbose_name': 'Կոնտակտային տվյալ',
                'verbose_name_plural': 'Կոնտակտային տվյալներ',
            },
        ),
    ]
