# Generated by Django 3.2 on 2022-06-02 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Օր.՝ 12:00 - 15:00', max_length=120, unique=True, verbose_name='Ժամանակահատված')),
            ],
            options={
                'verbose_name': 'Ամրագրման ժամ',
                'verbose_name_plural': 'Ամրագրման ժամեր',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Անուն')),
                ('phone', models.CharField(max_length=40, verbose_name='Հեռ.')),
                ('date_of_book', models.DateTimeField(verbose_name='Ամրագրման օրը')),
                ('time_of_pick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactus.workinghours', verbose_name='Ամրագրված ժամանակահատված')),
            ],
            options={
                'verbose_name': 'Ամրագրումներ',
                'verbose_name_plural': 'Ամրագրումներ',
            },
        ),
    ]
