# Generated by Django 4.0 on 2022-06-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_alter_bookings_id_alter_contactusjoinusdata_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuspage',
            name='breadcrumb_image',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='breadcrumbs_text',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='breadcrumbs_text_en',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='breadcrumbs_text_hy',
        ),
        migrations.RemoveField(
            model_name='contactuspage',
            name='breadcrumbs_text_ru',
        ),
    ]
