# Generated by Django 4.0 on 2022-06-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0006_remove_contactuspage_breadcrumb_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['my_order'], 'verbose_name': 'Ամրագրման ժամ', 'verbose_name_plural': 'Ամրագրման ժամեր'},
        ),
        migrations.AddField(
            model_name='workinghours',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
    ]
