# Generated by Django 3.1 on 2022-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['my_order'], 'verbose_name': 'Բրենդ', 'verbose_name_plural': 'Բրենդներ'},
        ),
        migrations.AddField(
            model_name='brand',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
    ]
