# Generated by Django 4.0.4 on 2022-05-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterfield',
            name='is_main',
        ),
    ]
