# Generated by Django 4.0.4 on 2022-05-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_filterfield_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='help_field_content',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='help_field_content_en',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='help_field_content_hy',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='help_field_content_ru',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='help_field_title',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='help_field_title_en',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='help_field_title_hy',
        ),
        migrations.RemoveField(
            model_name='filterfield',
            name='help_field_title_ru',
        ),
    ]
