# Generated by Django 4.0.4 on 2022-05-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_filterfield_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='breadcrumb_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='brand',
            name='breadcrumb_text_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='brand',
            name='breadcrumb_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description_hy',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title_hy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='filterfield',
            name='category',
            field=models.ManyToManyField(to='shop.brand', verbose_name='Բրենդ'),
        ),
    ]
