# Generated by Django 4.0.4 on 2022-05-30 18:26

import core.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_brand_breadcrumb_text_en_brand_breadcrumb_text_hy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='large_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='large_description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='large_description_hy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='large_description_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description_hy',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='breadcrumb_image',
            field=core.utils.CustomLogoField(default=1, upload_to='', verbose_name='Breadcrumb -ի նկար'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='breadcrumb_text',
            field=models.TextField(blank=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='category',
            name='breadcrumb_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='category',
            name='breadcrumb_text_hy',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='category',
            name='breadcrumb_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ'),
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
