# Generated by Django 4.0.4 on 2022-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_category_large_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Բաժին', 'verbose_name_plural': 'Բաժիններ'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.AddField(
            model_name='category',
            name='mptt_level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
