# Generated by Django 4.0.4 on 2022-05-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_options_remove_category_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Գույն', 'verbose_name_plural': 'Գույներ'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='my_order',
        ),
    ]
