# Generated by Django 4.0.4 on 2022-05-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_color_options_remove_color_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['my_order'], 'verbose_name': 'Գույն', 'verbose_name_plural': 'Գույներ'},
        ),
        migrations.AddField(
            model_name='color',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
    ]
