# Generated by Django 4.0.4 on 2022-05-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_color_options_color_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Գույն', 'verbose_name_plural': 'Գույներ'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='my_order',
        ),
    ]
