# Generated by Django 3.2 on 2022-05-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_color_options_color_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Անուն'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Անուն'),
        ),
    ]
