# Generated by Django 3.2 on 2022-05-31 20:42

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=core.utils.CustomLogoField(upload_to='product-img/'),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
