# Generated by Django 3.2 on 2022-06-01 20:00

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220531_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=core.utils.CustomLogoField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='breadcrumb_image',
            field=core.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Breadcrumb -ի նկար'),
        ),
    ]
