# Generated by Django 4.0.4 on 2022-05-30 12:37

import ckeditor_uploader.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Անուն')),
                ('name_hy', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Անուն')),
                ('url', models.URLField(verbose_name='Ամբողջական հղում')),
                ('url_hy', models.URLField(null=True, verbose_name='Ամբողջական հղում')),
                ('url_ru', models.URLField(null=True, verbose_name='Ամբողջական հղում')),
                ('url_en', models.URLField(null=True, verbose_name='Ամբողջական հղում')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', core.utils.CustomLogoField(upload_to='')),
                ('image_small', core.utils.CustomLogoField(upload_to='', verbose_name='Փոքր նկար')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_hy', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ամբողջական հղում')),
                ('url_hy', models.URLField(blank=True, null=True, verbose_name='Ամբողջական հղում')),
                ('url_ru', models.URLField(blank=True, null=True, verbose_name='Ամբողջական հղում')),
                ('url_en', models.URLField(blank=True, null=True, verbose_name='Ամբողջական հղում')),
            ],
            options={
                'verbose_name': 'Գլխավոր էջի սլայդ',
                'verbose_name_plural': 'Գլխավոր էջի սլայդեր',
            },
        ),
    ]
