# Generated by Django 4.0 on 2022-06-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutus_id_alter_aboutusbanner_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ouradvantages',
            options={'ordering': ['my_order'], 'verbose_name': 'Առավելություն', 'verbose_name_plural': 'Մեր առավելությունները'},
        ),
        migrations.RemoveField(
            model_name='aboutusbanner',
            name='url',
        ),
        migrations.RemoveField(
            model_name='aboutusbanner',
            name='url_en',
        ),
        migrations.RemoveField(
            model_name='aboutusbanner',
            name='url_hy',
        ),
        migrations.RemoveField(
            model_name='aboutusbanner',
            name='url_ru',
        ),
        migrations.AddField(
            model_name='ouradvantages',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Դասավորել'),
        ),
    ]
