# Generated by Django 4.0.4 on 2022-05-30 12:37

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', core.utils.CustomLogoField(blank=True, upload_to='')),
                ('text', models.CharField(max_length=255, verbose_name='Տեքստ')),
                ('text_hy', models.CharField(max_length=255, null=True, verbose_name='Տեքստ')),
                ('text_ru', models.CharField(max_length=255, null=True, verbose_name='Տեքստ')),
                ('text_en', models.CharField(max_length=255, null=True, verbose_name='Տեքստ')),
                ('name', models.CharField(max_length=255, verbose_name='Դաշտի անուն')),
                ('name_hy', models.CharField(max_length=255, null=True, verbose_name='Դաշտի անուն')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Դաշտի անուն')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Դաշտի անուն')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Հղում')),
                ('url_hy', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Հղում')),
                ('url_ru', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Հղում')),
                ('url_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Հղում')),
            ],
            options={
                'verbose_name': 'Կոնտակտային տվյալ',
                'verbose_name_plural': 'Կոնտակտային տվյալներ',
            },
        ),
        migrations.CreateModel(
            name='FooTerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Անուն')),
                ('name_hy', models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն')),
            ],
            options={
                'verbose_name': 'Footer -ի բաժին',
                'verbose_name_plural': 'Footer -ի բաժիններ',
            },
        ),
        migrations.CreateModel(
            name='SocialShareButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('icon', core.utils.CustomLogoField(upload_to='')),
                ('url', models.URLField(verbose_name='Ամբողջական հղում')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Անուն (alt)')),
            ],
            options={
                'verbose_name': 'Սոց. ցանցի լոգո',
                'verbose_name_plural': 'Սոց. ցանցերի լոգոներ',
            },
        ),
        migrations.CreateModel(
            name='FooterItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Անուն')),
                ('name_hy', models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='Անուն')),
                ('url', models.URLField(verbose_name='Ամբողջական հղում')),
                ('url_hy', models.URLField(null=True, verbose_name='Ամբողջական հղում')),
                ('url_ru', models.URLField(null=True, verbose_name='Ամբողջական հղում')),
                ('url_en', models.URLField(null=True, verbose_name='Ամբողջական հղում')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='footer.footercategory', verbose_name='Բաժին')),
            ],
            options={
                'verbose_name': 'Footer -ի հղումներ',
                'verbose_name_plural': 'Footer -ի հղումներ',
            },
        ),
    ]
