# Generated by Django 4.0.4 on 2022-05-30 12:37

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(choices=[('blog', 'Բլոգ'), ('contacts', 'Կապ'), ('faq', 'Հաճախակի տրվող հարցեր'), ('peri_tv', 'Peri TV')], max_length=150, unique=True, verbose_name='Ընտրեք էջը')),
                ('breadcrumbs_text', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_hy', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_ru', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_text_en', models.TextField(blank=True, null=True, verbose_name='Breadcrumb -ի տեքստ')),
                ('breadcrumbs_image', core.utils.CustomLogoField(blank=True, null=True, upload_to='', verbose_name='Breadcrumb -ի Նկար')),
                ('page_title', models.CharField(blank=True, max_length=255, verbose_name='Էջի վերնագիր')),
                ('page_title_hy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Էջի վերնագիր')),
                ('page_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Էջի վերնագիր')),
                ('page_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Էջի վերնագիր')),
            ],
            options={
                'verbose_name': 'Breadcrumb -ի կոնտենտ',
                'verbose_name_plural': 'Breadcrumb -ի կոնտենտ',
            },
        ),
    ]
