# Generated by Django 4.0.4 on 2022-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0002_alter_breadcrumbtexts_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='location',
            field=models.CharField(choices=[('blog', 'Բլոգ'), ('gallery', 'Տեսադարան'), ('contacts', 'Կապ'), ('abouts', 'Մեր մասին'), ('faq', 'Հաճախակի տրվող հարցեր'), ('peri_tv', 'Peri TV')], max_length=150, unique=True, verbose_name='Ընտրեք էջը'),
        ),
    ]
