# Generated by Django 4.0 on 2022-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0005_auto_20220602_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='location',
            field=models.CharField(choices=[('categories', 'Բաժինների էջ'), ('brands', 'Բրենդների էջ'), ('blog', 'Բլոգ'), ('gallery', 'Տեսադարան'), ('contacts', 'Կապ'), ('abouts', 'Մեր մասին'), ('faq', 'Հաճախակի տրվող հարցեր'), ('peri_tv', 'Peri TV')], max_length=150, unique=True, verbose_name='Ընտրեք էջը'),
        ),
    ]
