# Generated by Django 4.0 on 2022-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0006_alter_breadcrumbtexts_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumbtexts',
            name='location',
            field=models.CharField(choices=[('categories', 'Բաժինների էջ'), ('brands', 'Բրենդների էջ'), ('products', 'Collection -ի էջ'), ('blog', 'Բլոգ'), ('gallery', 'Տեսադարան'), ('contacts', 'Կապ'), ('abouts', 'Մեր մասին'), ('faq', 'Հաճախակի տրվող հարցեր'), ('peri_tv', 'Peri TV')], max_length=150, unique=True, verbose_name='Ընտրեք էջը'),
        ),
    ]
