# Generated by Django 4.0 on 2022-07-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0008_alter_breadcrumbtexts_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadcrumbtexts',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='breadcrumbtexts',
            name='page_title_en',
        ),
        migrations.RemoveField(
            model_name='breadcrumbtexts',
            name='page_title_hy',
        ),
        migrations.RemoveField(
            model_name='breadcrumbtexts',
            name='page_title_ru',
        ),
    ]
